version: '3.3'

services:
  fastapi-app-1:
    build:
      context: ./api-app
    ports:
      - "5000:5000"
      - "18000:18000"
    command: >
      sh -c "python fastapi-app.py bin/mnist-digitclassifier-model.keras"

  prometheus:
    build:
      context: ./prometheus
    ports:
      - "9090:9090"
